apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "rlinc"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "rlinc"
    spec:
      containers:
        - name: "rlinc"
          image: "aspdotnetreg.azurecr.io/rlinc"
          ports:
          - containerPort: 80