on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: aspdotnetreg.azurecr.io
        username: ${{ secrets.acr_aspdotnetreg_username }}
        password: ${{ secrets.acr_aspdotnetreg_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t aspdotnetreg.azurecr.io/rlinc:${{ github.sha }}
        docker push aspdotnetreg.azurecr.io/rlinc:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_rlinc_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep rlincc3f8 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace rlincc3f8`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: rlincc3f8
        container-registry-url: aspdotnetreg.azurecr.io
        container-registry-username: ${{ secrets.acr_aspdotnetreg_username }}
        container-registry-password: ${{ secrets.acr_aspdotnetreg_password }}
        secret-name: rlincdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: rlincc3f8
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          aspdotnetreg.azurecr.io/rlinc:${{ github.sha }}
        imagepullsecrets: |
          rlincdockerauth